#!/usr/bin/env php
<?php

declare(strict_types=1);

use Flytachi\Winter\Thread\Runnable;

// initialization
$fileAutoloader = dirname(__DIR__, 3) . '/bootstrap.php';
if (file_exists($fileAutoloader)) {
    require_once $fileAutoloader;
} else {
    fwrite(STDERR, "Error: No file bootstrap.php.\n");
    exit(1);
}

// 1. Reading all standard input data (stdin).
$payload = stream_get_contents(STDIN);

if (empty($payload)) {
    fwrite(STDERR, "Error: No payload received from stdin.\n");
    exit(1);
}

// 2. Configure
set_time_limit(0);
ob_implicit_flush();
ignore_user_abort(true);

// 3. Decode and deserialize the object Runnable.
if (function_exists('\Opis\Closure\serialize')) {
    $runnable = \Opis\Closure\unserialize(
        $payload,
        \Flytachi\Winter\Thread\Thread::getSerSecurity()
    );
} else {
    $runnable = unserialize($payload);
}

if (!$runnable instanceof Runnable) {
    fwrite(STDERR, "Error: The provided payload is not a valid RunnableInterface object.\n");
    exit(1);
}

// 4. Set the process title.
if (function_exists('cli_set_process_title')) {
    $options = getopt('', ['namespace::', 'name::', 'tag::']);
    $processNamespace = isset($options['namespace'])
        ? ($options['namespace'] . ' ') : '';
    $processTag = $options['tag'] ?? 'runnable';

    // Name
    if (isset($options['name'])) {
        $processName = $options['name'];
    } else {
        $className = get_class($runnable);
        $processName = substr($className, strrpos($className, '\\') + 1);
    }

    cli_set_process_title("WinterThread {$processNamespace}-> {$processName}@$processTag");
}

// 5. Let's complete the task.
try {
    $runnable->run();
    exit(0);
} catch (\Throwable $e) {
    fwrite(STDERR, "Uncaught exception in background process: " . $e->getMessage() . "\n");
    fwrite(STDERR, $e->getTraceAsString() . "\n");
    exit(1);
}
