services:
  server:
    container_name: ${COMPOSE_PROJECT_NAME:-app}
    network_mode: bridge
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVER_PORT: ${SERVER_PORT:-8000}
    environment:
      - COMPOSE_BAKE=true
      - DEV=${DEV:-false}
    ports:
      - "${SERVER_PORT:-8000}:${SERVER_PORT:-8000}"
    volumes:
      - ./:/var/www/html/
