<?php

declare(strict_types=1);

namespace Flytachi\Winter\K2\Unit\Operation;

use Flytachi\Winter\K2\Exception\Error;
use Flytachi\Winter\Thread\Thread;

/**
 * Represents a handle to an ongoing background operation.
 *
 * A Future is returned by {@see Operation::async()} and provides methods
 * to optionally await completion and retrieve the result of the background task.
 *
 * On construction, a "pending" marker is written to the shared store and
 * the underlying thread is started immediately. If the Future is destroyed
 * without calling {@see get()} or {@see return()}, the marker is deleted,
 * signaling the child process to discard its result (fire-and-forget).
 *
 * ---
 * ### Example 1: Awaiting a result
 *
 * ```
 * $future = Operation::async(function () {
 *     return computeHeavyResult();
 * });
 *
 * $value = $future->return(); // blocks until the task finishes
 * ```
 *
 * ---
 * ### Example 2: Fire-and-forget
 *
 * ```
 * $future = Operation::async(function () {
 *     sendWelcomeEmail($userId);
 * });
 *
 * return new Response('OK'); // $future goes out of scope → result discarded
 * ```
 * @template TResult
 *
 * @see Operation::async()
 * @see OpResult
 */
readonly class Future
{
    private OpResult $result;

    /**
     * Creates a new Future and immediately starts the background thread.
     *
     * @param string $id     The unique operation ID generated by {@see OperationRunnable}.
     * @param Thread $thread The thread that will execute the task.
     */
    public function __construct(
        private string $id,
        private Thread $thread
    ) {
        Operation::store()->write($this->id, 'pending');
        $thread->start();
    }

    public function join(): void
    {
        $this->thread->join();
        usleep(1_000);
    }

    /**
     * Blocks until the operation completes and returns its result.
     *
     * @return OpResult<TResult>
     * @throws Error If the result is not available after 3 retries.
     */
    public function get(): OpResult
    {
        if (!isset($this->result)) {
            $this->join();

            for ($i = 0; $i < 3; $i++) {
                $opResult = Operation::store()->read($this->id);
                if ($opResult) {
                    $this->result = $opResult;
                    Operation::store()->del($this->id);
                    break;
                }
                if ($i == 2) {
                    Error::throw('Operation result not found');
                }
                usleep(1_000);
            }
        }

        return $this->result;
    }

    /**
     * Awaits the operation and returns the raw result value.
     *
     * @param bool $isThrow Whether to re-throw any exception caught in the child process.
     * @return TResult
     * @throws \Throwable If $isThrow is true and the background task threw an exception.
     */
    public function return(bool $isThrow = true): mixed
    {
        $opResult = $this->get();
        if ($isThrow && $opResult->getThrowable()) {
            throw $opResult->getThrowable();
        }
        return $opResult->getResult();
    }

    public function __destruct()
    {
        Operation::store()->del($this->id);
    }
}
