<?php

declare(strict_types=1);

namespace Flytachi\Winter\Kernel\Unit\Operation;

use Flytachi\Winter\Kernel\Exception\Error;
use Flytachi\Winter\Thread\Thread;
use JetBrains\PhpStorm\Deprecated;

/**
 * Represents a handle to an ongoing background operation.
 *
 * A Future is returned by {@see Operation::async()} and provides methods
 * to optionally await completion and retrieve the result of the background task.
 *
 * On construction, a "pending" marker is written to the shared store and
 * the underlying thread is started immediately. If the Future is destroyed
 * without calling {@see get()} or {@see return()}, the marker is deleted,
 * signaling the child process to discard its result (fire-and-forget).
 *
 * ---
 * ### Example 1: Awaiting a result
 *
 * ```
 * $future = Operation::async(function () {
 *     return computeHeavyResult();
 * });
 *
 * $value = $future->return(); // blocks until the task finishes
 * ```
 *
 * ---
 * ### Example 2: Fire-and-forget
 *
 * ```
 * $future = Operation::async(function () {
 *     sendWelcomeEmail($userId);
 * });
 *
 * return new Response('OK'); // $future goes out of scope → result discarded
 * ```
 * @template TResult
 *
 * @package Flytachi\Winter\Kernel\Unit\Operation
 * @see Operation::async()
 * @see OpResult
 */
#[Deprecated]
readonly class Future
{
    /**
     * Cached result of the background operation.
     * Populated on the first call to {@see get()}.
     *
     * @var OpResult
     */
    private OpResult $result;

    /**
     * Creates a new Future and immediately starts the background thread.
     *
     * Writes a "pending" marker to the shared store under the given $id,
     * then calls {@see Thread::start()} to launch the child process.
     *
     * @param string $id     The unique operation ID generated by {@see OperationRunnable}.
     * @param Thread $thread The thread that will execute the task.
     */
    public function __construct(
        private string $id,
        private Thread $thread
    ) {
        Operation::store()->write($this->id, 'pending');
        $thread->start();
    }

    /**
     * Waits for the background thread to finish.
     *
     * Calls {@see Thread::join()} to block until the child process exits,
     * then sleeps for 1ms to allow the child to flush its result to the store.
     *
     * @return void
     */
    public function join(): void
    {
        $this->thread->join();
        usleep(1_000); // 0.001 seconds
    }

    /**
     * Blocks until the operation completes and returns its result.
     *
     * Calls {@see join()} internally on the first invocation.
     * The result is cached — subsequent calls return the cached {@see OpResult}
     * without re-joining or re-reading the store.
     *
     * After successfully reading the result, the store entry is deleted.
     * If the result is not available after 3 retries (with 1ms delays), an Error is thrown.
     *
     * @return OpResult<TResult> The result object containing the return value and/or any thrown exception.
     */
    public function get(): OpResult
    {
        if (!isset($this->result)) {
            $this->join();

            for ($i = 0; $i < 3; $i++) {
                $opResult = Operation::store()->read($this->id);
                if ($opResult) {
                    $this->result = $opResult;
                    Operation::store()->del($this->id);
                    break;
                }
                if ($i == 2) {
                    Error::throw('Operation result not found');
                }
                usleep(1_000);
            }
        }

        return $this->result;
    }

    /**
     * Awaits the operation and returns the raw result value.
     *
     * A convenience wrapper around {@see get()} that unwraps the {@see OpResult}.
     *
     * @param bool $isThrow Whether to re-throw any exception caught in the child process.
     *                      Defaults to true. Pass false to suppress exceptions and return null instead.
     *
     * @return TResult The return value of the background callback, or null if it returned void.
     *
     * @throws \Throwable If $isThrow is true and the background task threw an exception.
     */
    public function return(bool $isThrow = true): mixed
    {
        $opResult = $this->get();
        if ($isThrow && $opResult->getThrowable()) {
            throw $opResult->getThrowable();
        }
        return $opResult->getResult();
    }

    /**
     * Cleans up the store entry when the Future is destroyed.
     *
     * If {@see get()} was never called (fire-and-forget usage), this deletes
     * the "pending" marker, signaling the child process to discard its result
     * and preventing orphaned data from accumulating in the store.
     */
    public function __destruct()
    {
        Operation::store()->del($this->id);
    }
}
